import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Indie_Flower } from 'next/font/google'

import './globals.css'


const inter = Inter({
   weight: '800',
   subsets: ['latin'] });

export const indie = Indie_Flower({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-indie'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <section className={inter.className}>
            <a>Main Site</a>
          </section>

        </nav>
        {children}
      
      
      </body>
    </html>
  )
}
